# Exercises

In [ ]:
# Question 1 -
#Calculate the BMI (body mass index) on the two lists below using NDArrays...¶


In [3]:
import numpy as np
# formula = weight / (height**2) * 730
height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

bmi = weight / (height **2) * 730
bmi






array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

In [7]:
print('Here is a 4x4 matrix with numbers between 0 and 31: \n %s' % np.random.uniform (0,31, (4,4)))

Here is a 4x4 matrix with numbers between 0 and 31: 
 [[ 6.69216307 21.4260084  15.79780451  2.35879704]
 [14.69025473 27.90829346 16.12440167 24.51453161]
 [12.93734628  6.7248726   8.901839    7.63879151]
 [ 1.53706006  0.62566431  0.32880488  4.7407415 ]]


In [16]:
def makeMatrix(low, high, shape):
    
    return np.random.uniform (0,31,(4,4))

print(makeMatrix(0,31,(4,4)))


[[ 8.93767736  6.42512359 26.93594242 10.0361026 ]
 [24.17353002 19.98083586 29.30004652 25.46513274]
 [29.35086967 19.09774054  5.39529653 22.87714227]
 [14.05633347 10.4880729  23.45309318 21.89478706]]


### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [ ]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass

### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [47]:
import csv
import numpy as np

#Test to make sure you have the correct data

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]



# instead of loading csv normally, let's load it into a numpy array to calculate results on

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../files/redsox_2017_hitting.txt')

slg_2017 = np.array(sorted(bs2017['SLG'][0:20]))

#print(slg_2017)

bs2018 = load_data('../files/redsox_2018_hitting.txt')

slg_2018 = np.array(sorted(bs2018['SLG'][0:20]))

#print(slg_2018)

result_diff = slg_2018 - slg_2017
result_diff

print ("Of the 20 evaluated players, " + str(len([x for x in result_diff if x > 0])) + " had a higher slugging percentage in 2018")
                   



Of the 20 evaluated players, 13 had a higher slugging percentage in 2018


In [109]:
"""
The best way to evaluate the slugging percentage in a year over year basis
would be to calculate the entire team's slugging percentage in 2018 vs
2017. Mike Lowell and Mookie Betta were filthy in 2018.  Slugging 
percentage can be determined from the dataset you have by 
using the following principles:

AB is the denominator
The numerator is 2 * 2B + 3 * 3B + 4 * HR - (H - 2B - 3B - HR)

The Red Sx=ox slugged .454 in 2018 vs .408 in 2017

"""
import csv
import numpy as np

#Test to make sure you have the correct data

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

bs2017 = load_data('../files/redsox_2017_hitting.txt')
bs2018 = load_data('../files/redsox_2018_hitting.txt')

hits_2017 = (bs2017['H'])
AB_2017 = bs2017['AB']
DB_2017 = bs2017['2B']
Triple_2017 = bs2017['3B'] 
HR_2017 = bs2017['HR']


total_bases_2017 = (sum(hits_2017) + sum(DB_2017) + sum(Triple_2017)*2 + sum(HR_2017)*3)
total_ab_2017 = (sum(AB_2017))
SLG_2017 = total_bases_2017 / total_ab_2017
print(SLG_2017)

hits_2018 = (bs2018['H'])
AB_2018 = bs2018['AB']
DB_2018 = bs2018['2B']
Triple_2018 = bs2018['3B'] 
HR_2018 = bs2018['HR']


total_bases_2018 = (sum(hits_2018) + sum(DB_2018) + sum(Triple_2018)*2 + sum(HR_2018)*3)
total_ab_2018 = (sum(AB_2018))
SLG_2018 = total_bases_2018 / total_ab_2018
print(SLG_2018)



0.4076500796883301
0.4539614561027837


In [53]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

